config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/whack_a_mole' => 'pages#whack_a_mole', :as => 'whack_a_mole'
  get '/connect_4' => 'pages#connect_4', :as => 'connect_4'
  get '/car_game' => 'pages#car_game', :as => 'car_game'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnaOSantos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('favicon.png') %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/car_game.html.erb
<body>
  <div class="score"></div>
    <div class="game" style="height:90vh">
        <div class="startScreen">Press here to Start
            <br>Arrow keys to move
            <br>If you hit a another car you will lose.</div>
        <div class="gameArea"></div>
    </div>
</body>

app/views/pages/connect_4.html.erb
  <header>
  <h1>Connect 4</h1>
  <div class="reset text-center">
    <p>Reset</p>
  </div>
    <h3 class="player-turn"></h3>
    <div id="player1">
      <p>Player 1 - Write Your Name</p>
      <input type="text">
      <p class="playerColor"></p>
    </div>
    <div id="player2">
      <p>Player 2 - Write Your Name</p>
      <input type="text">
      <p class="playerColor"></p>
    </div>
  </header>
    <div class="game-4">
    <table>
      <tr>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
      </tr>
      <tr>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
      </tr>
      <tr>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
      </tr>
      <tr>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
      </tr>
      <tr>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
      </tr>
      <tr>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
        <td class="slot"></td>
      </tr>
    </table>
  </div>

app/views/pages/home.html.erb
<div class="container outer">
  <div class="d-flex justify-content-end social">
    <p><a href="https://mail.google.com/">ana.o.santus@gmail.com</a></p><p><a href="https://www.linkedin.com/in/ana-santos-71982299/">linkedin</a></p><p><a href="https://github.com/Ana-OS">github</a></p>
  </div>
  <div class="container d-flex mt-4 inner">
    <div class="name"><h1>Ana O. Santos</h1></div>
    <div class="container_pic"><img class="pic" src="https://res.cloudinary.com/dhjbcdzxb/image/upload/v1612461668/ana_santos1_copy_fvmttl.jpg" alt=""></div>
    <div class="container about"><p>Hi! I'm Ana and I'm a software developer.</p><p class="mt-5">I started my professional career in digital marketing but realized that software development is my true passion.</p></div>
  </div>
  <div class="text-center arrow" id="arrow"><i class="mt-4 fas fa-long-arrow-alt-down"></i></div>
</div>

<div class="content mx-auto" id="content-apps">
  <h3 class="mt-5 mb-5" id="app">Apps</h3>
  <div class="wrapper mt-5 d-flex justify-content-between">

    <div class="rentapool">
      <h5 class="title mb-2">Splash</h5>
      <div class="app mb-5">
        <a href="http://www.rentapool.today/"><img src="<%= asset_path('rentapool.jpg') %>"  alt=""></a>
        <p class="ml-3 mr-3 mt-5">This app was developed as an Airbnb clone at Le Wagon coding bootcamp. It allows you to rent swimming pools worldwide.</p>
      </div>
    </div>
    <div class="beerware">
      <h5 class="title">Beerware</h5>
      <div class="app mb-5">
        <a href="http://www.beerware.online/"><img src="<%= asset_path('beerware.png') %>" alt=""></a>
        <p class="ml-3 mr-3 mt-5">This is an exclusively<span> Mobile App </span>that allows  you to discover bars speciallized in craft beers in the city of Lisbon.</p>
      </div>
    </div>
    <div class="cocktails">
      <h5 class="title">The Cocktail Diary</h5>
      <div class="app mb-3">
        <a href="https://the-cocktail-diary.herokuapp.com/"><img src="<%= asset_path('cocktail_diary.jpg') %>" alt=""></a>
        <p class="ml-3 mr-3 mt-5">With this diary you can keep a list of your favorite cocktails ingredients and access other's for inspiration.</p>
      </div>
    </div>
  </div>
  <div style="height:100px"></div>
  <h3 class="mt-5 games-title" style="display: none">Javascript Games for Desktop</h3>
  <div class="wrapper mt-5 d-flex justify-content-between"  >
    <div class="connect-4"style="display:none">
      <h5 class="mt-3">Whack A Mole</h5>
      <%= link_to whack_a_mole_path, data: { turbolinks: false } do %>
        <div class="app"style="display:none">
          <img src="<%= asset_path('mole.png')%>" alt="" class="mt-4" style="width:200px; height:200px">
        </div>
      <% end %>
    </div>
    <div class="space-invaders"style="display:none">
      <h5 class="">Car Game</h5>
      <%= link_to car_game_path, data: { turbolinks: false } do %>
        <div class="app">
          <img class="mt-3" src="<%= asset_path('car-game.jpg')%>" alt="" style="width:260px; height:180px">
        </div>
      <% end %>
    </div>

    <div class="memory-game"style="display:none">
      <h5 class="mt-1">Connect 4</h5>
      <%= link_to connect_4_path, data: { turbolinks: false } do %>
        <div class="app">
          <img class="mt-3" src="<%= asset_path('connect-four.jpg')%>" alt=""  style="width:230px; height:190px">
        </div>
      <% end %>
  </div>
</div>

app/views/pages/whack_a_mole.html.erb
<div class="container-mole col-12"  >
  <header class="mt-5">
    <h1>Whack-a-mole! <span class="score-mole">0</span></h1>
    <h2 class="timeUp hidden">TIME'S UP!<span class="playAgain">Click "start" to play again<span></h2>
    <button class="start">Start!</button>
  </header>

  <div class="mole-game">
    <div class="hole hole1">
      <div class="mole"></div>
    </div>
    <div class="hole hole2">
      <div class="mole"></div>
    </div>
    <div class="hole hole3">
      <div class="mole"></div>
    </div>
    <div class="hole hole4">
      <div class="mole"></div>
    </div>
    <div class="hole hole5">
      <div class="mole"></div>
    </div>
    <div class="hole hole6">
      <div class="mole"></div>
    </div>
  </div>
</div>